# Site settings
title: MobileSpace
email: helloomonte@gmail.com
copyright_name: MobileSpace
github_username: mobilespace

collections:
  vehicles :
  teams:
  subteam :
  competition :
  research :
  people:

# used to estimate reading time
wpm: 150

port: 4444
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
